In [1]:
!pip3 install numpy


In [2]:
!pip3 install numpy

In [5]:
import numpy as np
import time

In [12]:
#execution performance
size = 1_000_0000
py_list = list(range(size))#1,2,3,4.............
start = time.time()
sq_list=[x**2 for x in py_list]
end = time.time()
print(f"python list time={end-start}seconds")


#numpy arrays  


np_arr=np.array(py_list)
start=time.time()
#vectorization

end=time.time()
print(f"numpy array time={end-start}seconds")


python list time=3.424466609954834seconds
numpy array time=0.0001862049102783203seconds


In [4]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [14]:
#memory 
print(f"python list size={sys.getsizeof(py_list)*len(py_list)}bytes")

print(f"python list size={np_arr.nbytes} bytes")




python list size=800000560000000bytes
python list size=80000000 bytes


In [19]:
#create from lists
arr=np.array([1,2,3,4,5])
print(arr,type(arr))
arr1=np.array([1,2,3,4,5,"shivam"])
print(arr1,type(arr1))
arr2D=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'shivam'] <class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]] (3, 4)


In [21]:
#create
arr1=np.zeros((2,3))#prefill
print(arr1,arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [22]:
#create
arr1=np.ones((2,3))#prefill
print(arr1,arr1.shape)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [24]:
#create
arr1=np.full((5,5),11)#prefill
print(arr1,arr1.shape)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]] (5, 5)


In [26]:
#identity matrix
#create
arr1=np.eye((3))
print(arr1,arr1.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [32]:
#range function
#range(start,end,step)
arr5=np.arange(1,10)
print(arr5,arr5.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [33]:
arr5=np.linspace(0,100,4)#evenly spaced arrays
print(arr5,arr5.shape)

[  0.          33.33333333  66.66666667 100.        ] (4,)


In [36]:
#properties
arr=np.array([[1,2,3,4,5],[2,5,8,7,9]])
print(arr.shape)#dimensions =mxn
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(2, 5)
10
int64
2


In [42]:
#operations
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

#reshaping

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

#flatened

flattened = arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [43]:
#indexing
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[2])

1
3


In [44]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1][1])


5


In [47]:
#fancy indexing
arr=np.array([1,2,3,4,5,6,7])
idx=[0,1,3,5,6]
print(arr[idx])

[1 2 4 6 7]


In [50]:
#slicing
arr = np.array([1,2,3,4,5])
#[start,end,step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])

[2 3 4]
[2 3 4 5]
[1 2 3 4]


nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
arr = np.array([1,2,3,4,5])

In [52]:
nums=[1,2,3,4,5]
sub_list=nums[1:3] 
print(sub_list)
arr = np.array([1,2,3,4,5])

[2, 3]


In [55]:
#Data types
arr=np.array([1,2,3.14,4,5])
print(arr,arr.dtype)

[1.   2.   3.14 4.   5.  ] float64
